-- =====================================================
-- PART 3 - VALIDATION QUERIES
-- Day 7 SQL Detective Day
-- =====================================================

-- =====================================================
-- V1 - Count all orders
-- Purpose: Verify the total number of orders.
-- =====================================================
SELECT COUNT(*) AS total_orders
FROM orders;


-- =====================================================
-- V2 - Count completed orders
-- Purpose: Verify how many completed orders exist.
-- =====================================================
SELECT COUNT(*) AS completed_orders
FROM orders
WHERE status = 'completed';


-- =====================================================
-- V3 - Count pending orders
-- Purpose: Verify how many pending orders exist.
-- =====================================================
SELECT COUNT(*) AS pending_orders
FROM orders
WHERE status = 'pending';


-- =====================================================
-- V4 - Count cancelled orders
-- Purpose: Verify how many cancelled orders exist.
-- =====================================================
SELECT COUNT(*) AS cancelled_orders
FROM orders
WHERE status = 'cancelled';


-- =====================================================
-- V5 - Count all customers
-- Purpose: Verify the number of customers.
-- =====================================================
SELECT COUNT(*) AS total_customers
FROM customers;


-- =====================================================
-- V6 - Count all products
-- Purpose: Verify the number of products.
-- =====================================================
SELECT COUNT(*) AS total_products
FROM products;


-- =====================================================
-- V7 - Calculate completed revenue only
-- Purpose: Revenue should only include completed orders.
-- =====================================================
SELECT SUM(quantity * price) AS completed_revenue
FROM orders
JOIN products
    ON orders.product_id = products.product_id
WHERE status = 'completed';


-- =====================================================
-- V8 - Calculate completed revenue by product
-- Purpose: Verify revenue generated by each product.
-- =====================================================
SELECT product_name,
       SUM(quantity * price) AS revenue
FROM orders
JOIN products
    ON orders.product_id = products.product_id
WHERE status = 'completed'
GROUP BY product_name
ORDER BY revenue DESC;


-- =====================================================
-- V9 - Calculate completed revenue by category
-- Purpose: Verify revenue generated by each category.
-- =====================================================
SELECT category,
       SUM(quantity * price) AS revenue
FROM orders
JOIN products
    ON orders.product_id = products.product_id
WHERE status = 'completed'
GROUP BY category
ORDER BY revenue DESC;


-- =====================================================
-- V10 - Count orders by city
-- Purpose: Verify order activity for each city.
-- =====================================================
SELECT customers.city,
       COUNT(*) AS order_count
FROM orders
JOIN customers
    ON orders.customer_id = customers.customer_id
GROUP BY customers.city
ORDER BY order_count DESC;


-- =====================================================
-- V11 - Find customers with more than one order
-- Purpose: Identify repeat customers.
-- =====================================================
SELECT customer_id,
       COUNT(*) AS order_count
FROM orders
GROUP BY customer_id
HAVING COUNT(*) > 1
ORDER BY order_count DESC;


-- =====================================================
-- V12 - Find the top 3 completed orders by total amount
-- Purpose: Show the three highest-value completed orders.
-- =====================================================
SELECT order_id,
       quantity,
       price,
       quantity * price AS total_amount
FROM orders
JOIN products
    ON orders.product_id = products.product_id
WHERE status = 'completed'
ORDER BY total_amount DESC
LIMIT 3;


-- =====================================================
-- V13 - Find orders that should not count as revenue
-- Purpose: Display pending and cancelled orders.
-- =====================================================
SELECT *
FROM orders
WHERE status <> 'completed';


-- =====================================================
-- V14 - Find the category with the highest completed revenue
-- Purpose: Determine the best-performing product category.
-- =====================================================
SELECT category,
       SUM(quantity * price) AS revenue
FROM orders
JOIN products
    ON orders.product_id = products.product_id
WHERE status = 'completed'
GROUP BY category
ORDER BY revenue DESC
LIMIT 1;


-- =====================================================
-- V15 - Find the city with the highest order activity
-- Purpose: Determine which city has the most orders.
-- =====================================================
SELECT customers.city,
       COUNT(*) AS order_count
FROM orders
JOIN customers
    ON orders.customer_id = customers.customer_id
GROUP BY customers.city
ORDER BY order_count DESC
LIMIT 1;